---
# file: dream.yml

# Gather facts
- hosts: all
  tags: verify
  tasks:
    - setup:

- hosts: dream
  tags: caffe
  sudo: yes
  roles: [caffe]

- hosts: dream-STOP
  tags: ipython
  roles: [ipython]
  sudo: yes

- hosts: dream-STOP
  tags: googlemodel
  sudo: yes
  vars:
    caffe_dir: /home/ubuntu/caffe
  tasks: 
    - name: fetch model
      get_url: dest={{ caffe_dir }}/models/bvlc_googlenet
        url=http://dl.caffe.berkeleyvision.org/bvlc_googlenet.caffemodel
